name: option
description: OPTION - Aplicativo de mobilidade urbana com Material Design 3.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  geolocator: ^13.0.1
  geolocator_android: ^4.6.2
  geocoding: ^2.1.1
  provider: ^6.1.1
  google_maps_flutter: ^2.9.0

  supabase_flutter: ^2.8.0
  image_picker: ^1.1.2
  image: ^4.1.7
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  mask_text_input_formatter: ^2.9.0
  
  # Monitoring dependencies
  logger: ^2.4.0
  # sentry_flutter: ^7.14.0
  dio: ^5.7.0
  package_info_plus: ^8.0.2
  
  # OneSignal dependencies
  onesignal_flutter: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/