-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.app_users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text NOT NULL DEFAULT 'pending'::text UNIQUE,
  photo_url text,
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['passenger'::text, 'driver'::text, 'admin'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text, 'pending'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fcm_token text,
  device_id text,
  device_platform text CHECK (device_platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])),
  last_active_at timestamp with time zone DEFAULT now(),
  profile_complete boolean NOT NULL DEFAULT false,
  CONSTRAINT app_users_pkey PRIMARY KEY (id),
  CONSTRAINT app_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.asaas_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asaas_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  payment_id text,
  payload jsonb NOT NULL,
  processed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asaas_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.backup_app_users_migration (
  id uuid,
  email text,
  full_name text,
  phone text,
  photo_url text,
  user_type text,
  status text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  user_id uuid
);
CREATE TABLE public.backup_conflict_409_removal (
  source_table text,
  backup_timestamp timestamp with time zone,
  id uuid,
  email text,
  full_name text,
  phone text,
  photo_url text,
  user_type text,
  status text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.backup_drivers_migration (
  id uuid,
  user_id uuid,
  cnh_number text,
  cnh_expiry_date date,
  cnh_photo_url text,
  vehicle_brand text,
  vehicle_model text,
  vehicle_year integer,
  vehicle_color text,
  vehicle_plate text,
  vehicle_category text,
  crlv_photo_url text,
  approval_status text,
  approved_by uuid,
  approved_at timestamp with time zone,
  is_online boolean,
  accepts_pet boolean,
  pet_fee numeric,
  accepts_grocery boolean,
  grocery_fee numeric,
  accepts_condo boolean,
  condo_fee numeric,
  stop_fee numeric,
  ac_policy text,
  custom_price_per_km numeric,
  custom_price_per_minute numeric,
  bank_account_type text,
  bank_code text,
  bank_agency text,
  bank_account text,
  pix_key text,
  pix_key_type text,
  consecutive_cancellations integer,
  total_trips integer,
  average_rating numeric,
  current_latitude numeric,
  current_longitude numeric,
  last_location_update timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.backup_passengers_migration (
  id uuid,
  user_id uuid,
  consecutive_cancellations integer,
  total_trips integer,
  average_rating numeric,
  payment_method_id text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.corrupted_users_backup (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_user_id uuid NOT NULL,
  original_full_name text,
  original_phone text,
  original_email text,
  correction_timestamp timestamp with time zone DEFAULT now(),
  correction_reason text,
  restored boolean DEFAULT false,
  restored_at timestamp with time zone,
  CONSTRAINT corrupted_users_backup_pkey PRIMARY KEY (id)
);
CREATE TABLE public.driver_approval_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  old_status text,
  new_status text,
  reason text,
  approved_documents jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_approval_audit_pkey PRIMARY KEY (id),
  CONSTRAINT driver_approval_audit_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  document_type text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type text,
  expiry_date date,
  rejection_reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  is_current boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::approval_status_enum,
  CONSTRAINT driver_documents_pkey PRIMARY KEY (id),
  CONSTRAINT driver_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.app_users(id),
  CONSTRAINT driver_documents_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_excluded_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  neighborhood_name text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_excluded_zones_pkey PRIMARY KEY (id),
  CONSTRAINT driver_excluded_zones_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  driver_distance_km numeric NOT NULL,
  driver_eta_minutes integer NOT NULL,
  base_fare numeric NOT NULL,
  additional_fees numeric NOT NULL,
  total_fare numeric NOT NULL,
  distance_component numeric,
  time_component numeric,
  is_available boolean DEFAULT true,
  was_selected boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_offers_pkey PRIMARY KEY (id),
  CONSTRAINT driver_offers_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT driver_offers_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.trip_requests(id)
);
CREATE TABLE public.driver_operation_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  zone_name text NOT NULL,
  polygon_coordinates jsonb NOT NULL,
  price_multiplier numeric NOT NULL DEFAULT 1.00 CHECK (price_multiplier >= 0.1 AND price_multiplier <= 10.0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_operation_zones_pkey PRIMARY KEY (id),
  CONSTRAINT driver_operation_zones_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_operational_cities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  city_id uuid NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_operational_cities_pkey PRIMARY KEY (id),
  CONSTRAINT driver_operational_cities_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT driver_operational_cities_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.operational_cities(id)
);
CREATE TABLE public.driver_schedule_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  override_start timestamp with time zone NOT NULL CHECK (override_start >= (now() - '01:00:00'::interval)),
  override_end timestamp with time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT driver_schedule_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT driver_schedule_overrides_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.drivers(id),
  CONSTRAINT driver_schedule_overrides_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT driver_schedules_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_status (
  driver_id uuid NOT NULL,
  online_intent boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT driver_status_pkey PRIMARY KEY (driver_id),
  CONSTRAINT driver_status_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  available_balance numeric DEFAULT 0,
  pending_balance numeric DEFAULT 0,
  total_earned numeric DEFAULT 0,
  total_withdrawn numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_wallets_pkey PRIMARY KEY (id),
  CONSTRAINT driver_wallets_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.drivers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  vehicle_brand text NOT NULL,
  vehicle_model text NOT NULL,
  vehicle_year integer NOT NULL,
  vehicle_color text NOT NULL,
  vehicle_plate text NOT NULL UNIQUE,
  vehicle_category text NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  is_online boolean DEFAULT false,
  accepts_pet boolean DEFAULT false,
  pet_fee numeric DEFAULT 0,
  accepts_grocery boolean DEFAULT false,
  grocery_fee numeric DEFAULT 0,
  accepts_condo boolean DEFAULT false,
  condo_fee numeric DEFAULT 0,
  stop_fee numeric DEFAULT 0,
  ac_policy text DEFAULT 'on_request'::text CHECK (ac_policy = ANY (ARRAY['always_on'::text, 'always_off'::text, 'on_request'::text])),
  custom_price_per_km numeric,
  custom_price_per_minute numeric,
  bank_account_type text CHECK (bank_account_type = ANY (ARRAY['checking'::text, 'savings'::text])),
  bank_code text,
  bank_agency text,
  bank_account text,
  pix_key text,
  pix_key_type text CHECK (pix_key_type = ANY (ARRAY['cpf'::text, 'cnpj'::text, 'email'::text, 'phone'::text, 'random'::text])),
  consecutive_cancellations integer DEFAULT 0,
  total_trips integer DEFAULT 0,
  average_rating numeric,
  current_latitude numeric,
  current_longitude numeric,
  last_location_update timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fcm_token text,
  device_platform text CHECK (device_platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])),
  last_notification_at timestamp with time zone,
  approval_status USER-DEFINED DEFAULT 'pending'::approval_status_enum,
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.app_users(id),
  CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id),
  CONSTRAINT drivers_vehicle_category_fkey FOREIGN KEY (vehicle_category) REFERENCES public.platform_settings(category)
);
CREATE TABLE public.location_sharing (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  shared_with_users ARRAY DEFAULT '{}'::uuid[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  CONSTRAINT location_sharing_pkey PRIMARY KEY (id),
  CONSTRAINT location_sharing_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.location_updates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sharing_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT location_updates_pkey PRIMARY KEY (id),
  CONSTRAINT location_updates_sharing_id_fkey FOREIGN KEY (sharing_id) REFERENCES public.location_sharing(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  body text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['trip'::text, 'promotion'::text, 'system'::text, 'chat'::text, 'payment'::text])),
  data jsonb,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text])),
  is_read boolean DEFAULT false,
  sent_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.operational_cities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  state text NOT NULL,
  country text DEFAULT 'Brasil'::text,
  is_active boolean DEFAULT true,
  min_fare numeric DEFAULT 8.00,
  launch_date date,
  polygon_coordinates jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT operational_cities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.passenger_promo_code_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  promo_code_id uuid NOT NULL,
  trip_id uuid,
  original_amount numeric NOT NULL CHECK (original_amount > 0::numeric),
  discount_amount numeric NOT NULL CHECK (discount_amount >= 0::numeric),
  final_amount numeric NOT NULL CHECK (final_amount >= 0::numeric),
  used_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT passenger_promo_code_usage_pkey PRIMARY KEY (id),
  CONSTRAINT passenger_promo_code_usage_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT passenger_promo_code_usage_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.passenger_promo_codes(id),
  CONSTRAINT passenger_promo_code_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.passenger_promo_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying, 'free_ride'::character varying]::text[])),
  value numeric NOT NULL CHECK (value > 0::numeric),
  min_amount numeric NOT NULL DEFAULT 0.00 CHECK (min_amount >= 0::numeric),
  max_discount numeric CHECK (max_discount IS NULL OR max_discount > 0::numeric),
  is_active boolean NOT NULL DEFAULT true,
  is_first_ride_only boolean NOT NULL DEFAULT false,
  usage_limit integer CHECK (usage_limit IS NULL OR usage_limit > 0),
  usage_count integer NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  valid_from timestamp with time zone NOT NULL DEFAULT now(),
  valid_until timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT passenger_promo_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.passenger_wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  passenger_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['credit'::character varying, 'trip_payment'::character varying, 'cashback'::character varying, 'refund'::character varying, 'cancellation_fee'::character varying]::text[])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  description text NOT NULL,
  trip_id uuid,
  payment_method_id uuid,
  asaas_payment_id character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT passenger_wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT passenger_wallet_transactions_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT passenger_wallet_transactions_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id),
  CONSTRAINT passenger_wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.passenger_wallets(id),
  CONSTRAINT passenger_wallet_transactions_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.passengers(id)
);
CREATE TABLE public.passenger_wallets (
  id uuid NOT NULL,
  passenger_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL UNIQUE,
  available_balance numeric NOT NULL DEFAULT 0.00 CHECK (available_balance >= 0::numeric),
  pending_balance numeric NOT NULL DEFAULT 0.00 CHECK (pending_balance >= 0::numeric),
  total_spent numeric NOT NULL DEFAULT 0.00 CHECK (total_spent >= 0::numeric),
  total_cashback numeric NOT NULL DEFAULT 0.00 CHECK (total_cashback >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT passenger_wallets_pkey PRIMARY KEY (id),
  CONSTRAINT passenger_wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT passenger_wallets_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.passengers(id)
);
CREATE TABLE public.passengers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  consecutive_cancellations integer DEFAULT 0,
  total_trips integer DEFAULT 0,
  average_rating numeric,
  payment_method_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT passengers_pkey PRIMARY KEY (id),
  CONSTRAINT passengers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['wallet'::character varying, 'credit_card'::character varying, 'debit_card'::character varying, 'pix'::character varying]::text[])),
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  card_data jsonb,
  pix_data jsonb,
  asaas_customer_id character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.platform_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL UNIQUE,
  base_price_per_km numeric NOT NULL,
  base_price_per_minute numeric NOT NULL,
  platform_commission_percent numeric NOT NULL,
  min_fare numeric DEFAULT 8.00,
  min_cancellation_fee numeric DEFAULT 10.00,
  cancellation_fee_percent numeric DEFAULT 20.00,
  no_show_wait_minutes integer DEFAULT 3,
  driver_acceptance_timeout_seconds integer DEFAULT 10,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promo_code_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  promo_code_id uuid NOT NULL,
  passenger_id uuid NOT NULL,
  trip_id uuid,
  discount_applied numeric,
  used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promo_code_usage_pkey PRIMARY KEY (id),
  CONSTRAINT promo_code_usage_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.passengers(id),
  CONSTRAINT promo_code_usage_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.promo_codes(id),
  CONSTRAINT promo_code_usage_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.promo_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  max_discount numeric,
  min_trip_value numeric,
  max_uses_per_user integer DEFAULT 1,
  valid_from timestamp with time zone NOT NULL,
  valid_until timestamp with time zone NOT NULL,
  usage_limit integer,
  used_count integer DEFAULT 0,
  target_cities ARRAY DEFAULT '{}'::uuid[],
  target_categories ARRAY DEFAULT '{}'::text[],
  is_first_trip_only boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
  CONSTRAINT promo_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL UNIQUE,
  passenger_rating integer CHECK (passenger_rating >= 1 AND passenger_rating <= 5),
  passenger_rating_tags ARRAY,
  passenger_rating_comment text,
  passenger_rated_at timestamp with time zone,
  driver_rating integer CHECK (driver_rating >= 1 AND driver_rating <= 5),
  driver_rating_tags ARRAY,
  driver_rating_comment text,
  driver_rated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.saved_places (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  label character varying NOT NULL,
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  category character varying NOT NULL DEFAULT 'other'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saved_places_pkey PRIMARY KEY (id),
  CONSTRAINT saved_places_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.trip_chats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trip_chats_pkey PRIMARY KEY (id),
  CONSTRAINT trip_chats_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.app_users(id),
  CONSTRAINT trip_chats_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.trip_location_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  speed_kmh numeric,
  heading numeric,
  accuracy_meters numeric,
  recorded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trip_location_history_pkey PRIMARY KEY (id),
  CONSTRAINT trip_location_history_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.trip_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  passenger_id uuid NOT NULL,
  origin_address text NOT NULL,
  origin_latitude numeric NOT NULL,
  origin_longitude numeric NOT NULL,
  origin_neighborhood text,
  destination_address text NOT NULL,
  destination_latitude numeric NOT NULL,
  destination_longitude numeric NOT NULL,
  destination_neighborhood text,
  vehicle_category text NOT NULL CHECK (vehicle_category = ANY (ARRAY['common_car'::text, 'freight'::text, 'tow_truck'::text])),
  needs_pet boolean DEFAULT false,
  needs_grocery_space boolean DEFAULT false,
  needs_ac boolean DEFAULT false,
  is_condo_origin boolean DEFAULT false,
  is_condo_destination boolean DEFAULT false,
  number_of_stops integer DEFAULT 0,
  status text DEFAULT 'searching'::text CHECK (status = ANY (ARRAY['searching'::text, 'driver_selected'::text, 'expired'::text, 'cancelled'::text])),
  selected_offer_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '00:00:10'::interval),
  target_driver_id uuid,
  fallback_drivers ARRAY,
  accepted_by_driver_id uuid,
  accepted_at timestamp with time zone,
  current_fallback_index integer DEFAULT 0,
  timeout_count integer DEFAULT 0,
  estimated_distance_km numeric,
  estimated_duration_minutes integer,
  estimated_fare numeric,
  CONSTRAINT trip_requests_pkey PRIMARY KEY (id),
  CONSTRAINT trip_requests_target_driver_id_fkey FOREIGN KEY (target_driver_id) REFERENCES public.drivers(id),
  CONSTRAINT trip_requests_accepted_by_driver_id_fkey FOREIGN KEY (accepted_by_driver_id) REFERENCES public.drivers(id),
  CONSTRAINT trip_requests_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.passengers(id)
);
CREATE TABLE public.trip_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL,
  old_status text,
  new_status text NOT NULL,
  changed_by uuid,
  reason text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trip_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT trip_status_history_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.trip_stops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL,
  stop_order integer NOT NULL,
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  arrived_at timestamp with time zone,
  departed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trip_stops_pkey PRIMARY KEY (id),
  CONSTRAINT trip_stops_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_code text NOT NULL UNIQUE,
  request_id uuid,
  passenger_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['driver_assigned'::text, 'driver_arriving'::text, 'waiting_passenger'::text, 'in_progress'::text, 'completed'::text, 'cancelled_by_passenger'::text, 'cancelled_by_driver'::text, 'no_show'::text])),
  origin_address text NOT NULL,
  origin_latitude numeric NOT NULL,
  origin_longitude numeric NOT NULL,
  origin_neighborhood text,
  destination_address text NOT NULL,
  destination_latitude numeric NOT NULL,
  destination_longitude numeric NOT NULL,
  destination_neighborhood text,
  vehicle_category text NOT NULL,
  needs_pet boolean DEFAULT false,
  needs_grocery_space boolean DEFAULT false,
  is_condo_destination boolean DEFAULT false,
  is_condo_origin boolean DEFAULT false,
  needs_ac boolean DEFAULT false,
  number_of_stops integer DEFAULT 0,
  route_polyline text,
  estimated_distance_km numeric,
  estimated_duration_minutes integer,
  driver_to_pickup_distance_km numeric,
  driver_to_pickup_duration_minutes integer,
  actual_distance_km numeric,
  actual_duration_minutes integer,
  waiting_time_minutes integer,
  driver_distance_traveled_km numeric,
  base_fare numeric NOT NULL,
  additional_fees numeric DEFAULT 0,
  surge_multiplier numeric DEFAULT 1.0,
  total_fare numeric NOT NULL,
  platform_commission numeric,
  driver_earnings numeric,
  cancellation_reason text,
  cancellation_fee numeric,
  cancelled_by text CHECK (cancelled_by = ANY (ARRAY['passenger'::text, 'driver'::text, 'system'::text])),
  created_at timestamp with time zone DEFAULT now(),
  driver_assigned_at timestamp with time zone,
  driver_arrived_at timestamp with time zone,
  trip_started_at timestamp with time zone,
  trip_completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  payment_id text,
  payment_completed_at timestamp with time zone,
  promo_code_id uuid,
  discount_applied numeric,
  updated_at timestamp with time zone DEFAULT now(),
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  requested_at timestamp with time zone,
  completed_at timestamp with time zone,
  assigned_at timestamp with time zone,
  arrived_at timestamp with time zone,
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.trip_requests(id),
  CONSTRAINT trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT trips_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.passengers(id)
);
CREATE TABLE public.user_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_token text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['ios'::text, 'android'::text])),
  device_model text,
  app_version text,
  os_version text,
  is_active boolean DEFAULT true,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_devices_pkey PRIMARY KEY (id),
  CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['earning'::text, 'withdrawal'::text, 'fee'::text, 'bonus'::text, 'penalty'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  description text,
  reference_type text,
  reference_id uuid,
  balance_after numeric,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'reversed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.driver_wallets(id)
);
CREATE TABLE public.withdrawals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  wallet_id uuid NOT NULL,
  amount numeric NOT NULL,
  withdrawal_method text CHECK (withdrawal_method = ANY (ARRAY['pix'::text, 'bank_transfer'::text])),
  bank_account_info jsonb,
  asaas_transfer_id text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  failure_reason text,
  requested_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT withdrawals_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawals_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.driver_wallets(id),
  CONSTRAINT withdrawals_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.working_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT working_hours_pkey PRIMARY KEY (id)
);