// Mocks generated by Mockito 5.4.6 from annotations
// in option/test/widget/working_hours_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:option/models/supabase/working_hours.dart' as _i2;
import 'package:option/services/working_hours_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkingHours_0 extends _i1.SmartFake implements _i2.WorkingHours {
  _FakeWorkingHours_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkingHoursService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkingHoursService extends _i1.Mock
    implements _i3.WorkingHoursService {
  MockWorkingHoursService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.WorkingHours>> getWorkingHours(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkingHours,
          [driverId],
        ),
        returnValue:
            _i4.Future<List<_i2.WorkingHours>>.value(<_i2.WorkingHours>[]),
      ) as _i4.Future<List<_i2.WorkingHours>>);

  @override
  _i4.Future<List<_i2.WorkingHours>> getWorkingHoursByDay(
    String? driverId,
    int? dayOfWeek,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkingHoursByDay,
          [
            driverId,
            dayOfWeek,
          ],
        ),
        returnValue:
            _i4.Future<List<_i2.WorkingHours>>.value(<_i2.WorkingHours>[]),
      ) as _i4.Future<List<_i2.WorkingHours>>);

  @override
  _i4.Future<_i2.WorkingHours> createWorkingHours({
    required String? driverId,
    required int? dayOfWeek,
    required _i5.TimeOfDay? startTime,
    required _i5.TimeOfDay? endTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkingHours,
          [],
          {
            #driverId: driverId,
            #dayOfWeek: dayOfWeek,
            #startTime: startTime,
            #endTime: endTime,
          },
        ),
        returnValue: _i4.Future<_i2.WorkingHours>.value(_FakeWorkingHours_0(
          this,
          Invocation.method(
            #createWorkingHours,
            [],
            {
              #driverId: driverId,
              #dayOfWeek: dayOfWeek,
              #startTime: startTime,
              #endTime: endTime,
            },
          ),
        )),
      ) as _i4.Future<_i2.WorkingHours>);

  @override
  _i4.Future<_i2.WorkingHours> updateWorkingHours(
    String? id, {
    int? dayOfWeek,
    _i5.TimeOfDay? startTime,
    _i5.TimeOfDay? endTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkingHours,
          [id],
          {
            #dayOfWeek: dayOfWeek,
            #startTime: startTime,
            #endTime: endTime,
          },
        ),
        returnValue: _i4.Future<_i2.WorkingHours>.value(_FakeWorkingHours_0(
          this,
          Invocation.method(
            #updateWorkingHours,
            [id],
            {
              #dayOfWeek: dayOfWeek,
              #startTime: startTime,
              #endTime: endTime,
            },
          ),
        )),
      ) as _i4.Future<_i2.WorkingHours>);

  @override
  _i4.Future<void> deleteWorkingHours(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkingHours,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllWorkingHours(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllWorkingHours,
          [driverId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isDriverWorkingNow(String? driverId) => (super.noSuchMethod(
        Invocation.method(
          #isDriverWorkingNow,
          [driverId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
