name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Usa imagem Flutter para evitar setup manual do SDK
    container: ghcr.io/cirruslabs/flutter:stable
    env:
      # Secrets devem ser configurados em Settings > Secrets and variables > Actions
      ASAAS_API_KEY: ${{ secrets.ASAAS_API_KEY }}
      # Sandbox por padrão no CI; ajuste conforme necessário
      ASAAS_BASE_URL: https://api-sandbox.asaas.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Check formatting
        run: |
          dart format --output=none --set-exit-if-changed .

      - name: Run tests
        run: flutter test

      - name: Build Web (release)
        run: |
          flutter build web --release \
            --dart-define=ASAAS_BASE_URL=${ASAAS_BASE_URL} \
            --dart-define=ASAAS_API_KEY=${ASAAS_API_KEY}

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  android-build:
    name: Android Build (APK release)
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      ASAAS_API_KEY: ${{ secrets.ASAAS_API_KEY }}
      ASAAS_BASE_URL: https://api-sandbox.asaas.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Pub get
        run: flutter pub get

      - name: Build APK (release)
        run: |
          flutter build apk --release \
            --dart-define=ASAAS_BASE_URL=${ASAAS_BASE_URL} \
            --dart-define=ASAAS_API_KEY=${ASAAS_API_KEY}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  ios-build:
    name: iOS Build (no codesign)
    runs-on: macos-latest
    needs: build-and-test
    env:
      ASAAS_API_KEY: ${{ secrets.ASAAS_API_KEY }}
      ASAAS_BASE_URL: https://api-sandbox.asaas.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: CocoaPods repo update
        working-directory: ios
        run: pod repo update

      - name: Build iOS (release, no codesign)
        run: |
          flutter build ios --no-codesign --release \
            --dart-define=ASAAS_BASE_URL=${ASAAS_BASE_URL} \
            --dart-define=ASAAS_API_KEY=${ASAAS_API_KEY}

      - name: Upload iOS Artifact (Runner.app)
        uses: actions/upload-artifact@v4
        with:
          name: ios-runner-app
          path: build/ios/iphoneos/Runner.app